config/routes.rb
Rails.application.routes.draw do

  root to: 'reservations#index'

  devise_for :companies, controllers: {
    sessions:      'companies/sessions',
    passwords:     'companies/passwords',
    registrations: 'companies/registrations'
  }
  devise_for :staffs, controllers: {
    sessions:      'staffs/sessions',
    passwords:     'staffs/passwords',
    registrations: 'staffs/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  resources :companies
  resources :branches
  resources :reservations do
    collection do
      get :list
    end
  end
  resources :rooms
  resources :timeframes do
    collection do
      post :single_duplicate
      post :multiple_duplicate
      post :time_based_multiple_duplicate
    end
  end
  resources :users
  resources :tickets
  resources :sales_items do
    collection do
      get :list
      post :purchase
    end
  end
  resources :staffs
  get "locale" => "application#locale", as: "locale"

  post "payments/customer_registration"
  post "payments/payjpcard_update"
  get 'payments/index'
  get "sml" => "payments#sml", as: "sml"
  post "payments/payjp_webhook"
  post "payments/charge"
  post "payments/subscribe"
  post "payments/unsubscribe"
  get "payments" => "payments#index", as: "payments"
  get "payment" => "payments#show", as: "payment"

end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  belongs_to :company
  belongs_to :branch

  enum status: { general: 1, admin: 3 }

end

app/controllers/staffs/confirmations_controller.rb
# frozen_string_literal: true

class Staffs::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/staffs/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Staffs::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/staffs/passwords_controller.rb
# frozen_string_literal: true

class Staffs::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/staffs/registrations_controller.rb
# frozen_string_literal: true

class Staffs::RegistrationsController < Devise::RegistrationsController
  # include Accessible
  # skip_before_action :check_user, except: [:new, :create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @all_secret_codes = Branch.all.pluck(:secret_code)
    build_resource
    yield resource if block_given?
    respond_with resource
  end

  def create
    # ここでUser.new（と同等の操作）を行う
    @all_secret_codes = Branch.all.pluck(:secret_code)
    build_resource(sign_up_params)
    @branch = Branch.where(secret_code: params[:staff][:secret_code]).first
    resource.branch_id = @branch.id
    resource.company_id = Company.find(@branch.company_id).id

     if resource.save
        # ブロックが与えられたらresource(=User)を呼ぶ
        yield resource if block_given?
        if company_admin
          redirect_to staffs_path(branch_id: resource.branch_id)
        else
          sign_up(resource_name, resource)
          redirect_to reservations_path(branch_id: resource.branch_id)
        end
     elsif resource.persisted?

       # confirmable/lockableどちらかのactive_for_authentication?がtrueだったら
       if resource.active_for_authentication?
  
         set_flash_message! :notice, :signed_up
         # AdminActionMailer.new_registration_reminder(resource).deliver
         # UserActionMailer.user_registration_reminder(resource).deliver
  
         
         if current_company.present?
           companies_path
         else
           respond_with resource, location: after_sign_up_path_for(resource)
         end
  
       else
         set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
         expire_data_after_sign_in!
         respond_with resource, location: after_inactive_sign_up_path_for(resource)
       end
     else
       clean_up_passwords resource
       set_minimum_password_length
       respond_with resource
     end
   end
  

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end


  def after_update_path_for(resource)
    edit_school_registration_path(resource)
  end
end

app/controllers/staffs/sessions_controller.rb
# frozen_string_literal: true

class Staffs::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  include Accessible
  skip_before_action :check_user, except: [:new, :create]
  # GET /resource/sign_in
  def new
    self.resource = resource_class.new(sign_in_params)
    clean_up_passwords(resource)
    yield resource if block_given?
    respond_with(resource, serialize_options(resource))
  end

  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    redirect_to reservations_path(branch_id: resource.company.branches.first.id)
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/staffs/unlocks_controller.rb
# frozen_string_literal: true

class Staffs::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  def index
    @staffs = Staff.where(branch_id: params[:branch_id])
    @branches = company_admin.branches
  end

  def edit
    @staff = Staff.find(params[:id])
  end

  def update
    @staff = Staff.find(params[:id])
    @staff.update(staff_params)
    if @staff.update(staff_params)
      redirect_to staffs_path(branch_id: @staff.branch_id), notice: t('activerecord.attributes.link.updated')
    else
      flash[:notice] = t('activerecord.attributes.link.failed_to_create')
      render 'staffs/edit'
    end
  end

  def destroy
    @staff = Staff.find(params[:id])
    branch_id = @staff.branch_id
    @staff.destroy
    redirect_to staffs_path(branch_id: branch_id), notice: t('activerecord.attributes.link.deleted')
  end

  private

    def staff_params
      params.require(:staff).permit(:name, :phone, :email, :status, :company_id, :branch_id)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/edit.html.slim
div.row
  div.col-md-12
    div class="card"
      div class="card-header text-white bg-secondary mb-3" 
        h4  = t('activerecord.attributes.user.edit')
      div class="card-body"
        == render 'shared/errors', obj: @staff
        = form_for @staff, url: staff_path do |f|
          div.col-md-12
            div.form-group
              = f.label :name
              = f.text_field :name, class:"form-control"
            div.form-group
              = f.label :email
              = f.text_field :email, class:"form-control"
            div.form-group
              = f.label :phone
              = f.text_field :phone, placeholder: t('activerecord.attributes.branch.phone_comment'), class:"form-control"
            div.form-group
              = f.label :status, t('activerecord.attributes.staff.status')
              br
              = f.select :status, Staff.statuses_i18n.map{|key,value| [value,key]}

          = f.submit  t('activerecord.attributes.link.update'), class:"btn btn-success button-margin"
br
br
= link_to :back do 
  button class="btn btn-secondary button-margin" = t("activerecord.attributes.link.back")

app/views/staffs/index.html.slim
= link_to t('activerecord.attributes.staff.signin'), new_staff_registration_path(branch_id: params[:branch_id]), class:"btn btn-success button-margin"
br
- if @branches.count > 0
  - @branches.each do |b|
    span#branch-button
      = link_to b.name, staffs_path(branch_id: b.id), class:"btn btn-secondary button-margin", name:"#{b.id}"

table class="table table-bordered"
  thead class="thead-dark table-active "
    tr
      th.text-center = "#"
      th = t('activerecord.attributes.staff.name')
      th = t('activerecord.attributes.staff.status')
      th = t('activerecord.attributes.staff.email')
      th = t('activerecord.attributes.staff.phone')
      th
      

  tbody
    - @staffs.each_with_index do |s,i| 
      tr 
        td.text-center = i + 1
        td = s.name
        td = s.status
        td = s.email
        td = s.phone
        - unless current_staff.present? && current_staff.id == s.id
          td 
            = link_to t('activerecord.attributes.link.edit'), edit_staff_path(id: s.id), class:"btn btn-success btn-sm button-margin"
            = link_to t('activerecord.attributes.link.delete'), staff_path(id: s.id), method: :delete, data: {confirm: t('activerecord.attributes.link.are_you_sure')}, class:"btn btn-danger btn-sm button-margin"
        
javascript:
  jQuery(function(){
    var params = (new URL(document.location)).searchParams;
    var branch_id = params.get('branch_id');
    $('#branch-button a').each(function(){
      var buttontype = $(this).attr('name');
      if( buttontype == branch_id ){
        $( $(this)).addClass("btn-company");
      }
    });
    //var branches = #{raw @branches.to_json};
  }) 