config/routes.rb
Rails.application.routes.draw do

  root to: 'reservations#index'

  devise_for :companies, controllers: {
    sessions:      'companies/sessions',
    passwords:     'companies/passwords',
    registrations: 'companies/registrations'
  }
  devise_for :staffs, controllers: {
    sessions:      'staffs/sessions',
    passwords:     'staffs/passwords',
    registrations: 'staffs/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  resources :companies
  resources :branches
  resources :reservations do
    collection do
      get :list
    end
  end
  resources :rooms
  resources :timeframes do
    collection do
      post :single_duplicate
      post :multiple_duplicate
      post :time_based_multiple_duplicate
    end
  end
  resources :users
  resources :tickets
  resources :sales_items do
    collection do
      get :list
      post :purchase
    end
  end
  resources :staffs
  get "locale" => "application#locale", as: "locale"

  post "payments/customer_registration"
  post "payments/payjpcard_update"
  get 'payments/index'
  get "sml" => "payments#sml", as: "sml"
  post "payments/payjp_webhook"
  post "payments/charge"
  post "payments/subscribe"
  post "payments/unsubscribe"
  get "payments" => "payments#index", as: "payments"
  get "payment" => "payments#show", as: "payment"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
  belongs_to :company
  has_many :staffs, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :timeframes, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :sales_items, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true
  validates :address, presence: true
end

app/models/colorlist.rb
class Colorlist < ActiveHash::Base
  self.data = [
    {id: 1, name: "赤(Red)", code: "#B22222"}, {id: 2, name: "青(Blue)", code: "#1E90FF"}, {id: 3, name: "緑(Green)", code: "#228B22"},
    {id: 4, name: "黄色(Yellow)", code: "#FFD700"},  {id: 5, name: "オレンジ(Orange)", code: "#FFA500"}, {id: 6, name: "ピンク(Pink)", code: "#EE82EE"},
    {id: 7, name: "灰色(Gray)", code: "#808080"}, {id: 8, name: "茶色(Brown)", code: "#A0522D"}
  ]
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :users, dependent: :destroy
  has_many :staffs, dependent: :destroy
  has_many :branches, dependent: :destroy
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :timeframe
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :branch
end

app/models/sales_item.rb
class SalesItem < ApplicationRecord
  validates :name, presence: true
  validates :number_of_ticket, presence: true
  validates :branch_id, presence: true
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  belongs_to :company
  belongs_to :branch

  enum status: { general: 1, admin: 3 }

end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :user
end

app/models/timeframe.rb
class Timeframe < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :colorlist
  belongs_to :branch
  belongs_to :room
  has_many :reservations, dependent: :destroy

  TIME_SPAN = 5.freeze
  START_TIME = Time.zone.local(2017, 1, 1, 7, 0).freeze
  END_TIME = Time.zone.local(2017, 1, 1, 23, 0).freeze

  validates :name, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :capacity, presence: true, numericality: true
  validates :color, presence: true
  validate :timeframe_duplicate
  validate :timeframe_span_check
  validate :timeframe_start_time_check
  validate :timeframe_end_time_check

  #バリデーション
  def date
    self.target_date
  end

  def timeframe_duplicate
    if self.branch.present? && Timeframe.where(target_date: target_date).where("room_id = ?", room_id)
      .where("start_time < ?", end_time).where("end_time > ?", start_time).where.not(id: self.id).where(branch_id: self.branch_id).present?
      errors.add(:start_time, ": ご入力いただいた時間帯にすでに時間枠が存在します。")
    end
  end

  def timeframe_span_check
    if start_time && start_time.strftime('%H:%M') >= end_time.strftime('%H:%M')
        errors.add(:start_time, :timeframe_start_time_should_be_smaller_than_end_time)
    end
  end

  def timeframe_start_time_check
    if start_time && start_time.strftime('%H:%M') < self.branch.calendar_start_time.strftime('%H:%M')
      errors.add(:start_time, :timeframe_start_time_should_be_within_calendar_start_time)
    end
  end

  def timeframe_end_time_check
    if end_time && end_time.strftime('%H:%M') > self.branch.calendar_end_time.strftime('%H:%M')
      errors.add(:end_time, :timeframe_end_time_should_be_within_calendar_end_time)
    end
  end


  #判定用
  def self.timeframe_duplicate?(timeframe)
    Timeframe.where("start_time <=?", timeframe.target_date.strftime("%Y-%m-%d") + " " + timeframe.end_time.strftime("%H:%M:%S"))
    .where("end_time >= ?", timeframe.target_date.strftime("%Y-%m-%d") + " " + timeframe.start_time.strftime("%H:%M:%S"))
    .where("room_id = ?", timeframe.room_id).present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :company
  belongs_to :branch
  has_many :reservations, dependent: :destroy
  has_many :tickets, dependent: :destroy
end

app/controllers/sales_items_controller.rb
class SalesItemsController < ApplicationController
  before_action :find_sales_item, only: [:show, :edit, :update, :delete]
  def customer_registration
  end
  
  def index
    @branches = company_admin.branches
    @sales_items = SalesItem.where(branch_id: params[:branch_id])
  end

  def list
    @branch = current_user.branch
    @sales_items = SalesItem.where(branch_id: @branch.id)
  end

  


  def show
    @sales_item = SalesItem.find(params[:id])
  end

  def new
    @sales_item = SalesItem.new
    @sales_item.branch_id = params[:branch_id]
  end

  def create
    @sales_item = SalesItem.create(sales_item_params)
    redirect_to sales_items_path(branch_id: @sales_item.branch_id), notice: t('activerecord.attributes.link.created')
  end

  def edit
  end

  def update
    if @sales_item.update(sales_item_params)
      redirect_to sales_items_path(id: @sales_item.id, branch_id: @sales_item.branch_id), notice: t('activerecord.attributes.link.updated')
    else
      flash[:notice] = t('activerecord.attributes.link.failed_to_create')
      render 'sales_items/edit'
    end
  end

  def destroy
    @sales_item.destroy
    redirect_to sales_items_path(id: @sales_item.id), notice: t('activerecord.attributes.link.deleted')
  end

  private
    def find_sales_item
      @sales_item = SalesItem.find(params[:id])
    end

    def sales_item_params
      params.require(:sales_item).permit(:name, :number_of_ticket, :branch_id, :price, :effective_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def devise_error_messages
    return "" if resource.errors.empty?
    html = ""
    # エラーメッセージ用のHTMLを生成
    messages = resource.errors.full_messages.each do |msg|
    html += <<-EOF
        <div class="error_field alert alert-danger" role="alert">
        <p class="error_msg">#{msg}</p>
        </div>
    EOF
    end
    html.html_safe
  end
end
  

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sales_items_helper.rb
module SalesItemsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/timeframes_helper.rb
module TimeframesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sales_items/_form.html.slim
div.col-md-12
  div.form-group
    = f.label :name
    = f.text_field :name, class:"form-control"
  div.form-group
    div.col-md-4
      = f.label :price
      div.input-group
        = f.number_field :price, default: 1000, class:"form-control"
        span.input-group-text = t('activerecord.attributes.sales_item.yen')
    div.col-md-4
      = f.label :number_of_ticket
      div.input-group
        = f.number_field :number_of_ticket, min: 1, class:"form-control" 
        span.input-group-text = t('activerecord.attributes.sales_item.sheet')
    div.col-md-4
      = f.label :effective_date
      div.input-group
        = f.number_field :effective_date, min: 1, class:"form-control" 
        span.input-group-text = t('activerecord.attributes.sales_item.date')

app/views/sales_items/edit.html.slim
div.row
  div.col-md-12
    div class="card"
      div class="card-header text-white bg-secondary mb-3" 
        h4  = t('activerecord.attributes.branch.edit')
      div class="card-body"
        == render 'shared/errors', obj: @sales_item
        = form_for @sales_item, url: sales_item_path do |f|
          == render 'sales_items/form', f: f
          = f.submit  t('activerecord.attributes.link.update'), class:"btn btn-info button-margin"
br
br
= link_to :back do 
  button class="btn btn-secondary button-margin" = t("activerecord.attributes.link.back")

app/views/sales_items/index.html.slim
= link_to t('activerecord.attributes.sales_item.new'), new_sales_item_path(branch_id: params[:branch_id]), class:"btn btn-success button-margin"
br
- if @branches.count > 0
  - @branches.each do |b|
    span#branch-button
      = link_to b.name, sales_items_path(branch_id: b.id), class:"btn btn-secondary button-margin", name:"#{b.id}"

table class="table table-bordered"
  thead class="thead-dark table-active "
    tr
      th.text-center = "#"
      th = t('activerecord.attributes.sales_item.name')
      th = t('activerecord.attributes.sales_item.price')
      th = t('activerecord.attributes.sales_item.number_of_ticket')
      th = t('activerecord.attributes.sales_item.effective_date')
      th

  tbody
    - @sales_items.each_with_index do |s,i| 
      tr 
        td.text-center = i + 1
        td = s.name
        td 
          = s.price 
          = t('activerecord.attributes.sales_item.yen')
        td 
          = s.number_of_ticket
          = t('activerecord.attributes.sales_item.sheet')
        td
          = s.effective_date
          = t('activerecord.attributes.sales_item.date')
        - unless current_staff.present? && current_staff.id == s.id
          td = link_to t('activerecord.attributes.link.edit'), edit_sales_item_path(id: s.id), class:"btn btn-success btn-sm"
        
javascript:
  jQuery(function(){
    var params = (new URL(document.location)).searchParams;
    var branch_id = params.get('branch_id');
    $('#branch-button a').each(function(){
      var buttontype = $(this).attr('name');
      if( buttontype == branch_id ){
        $( $(this)).addClass("btn-company");
      }
    });
    //var branches = #{raw @branches.to_json};
  }) 

app/views/sales_items/list.html.slim
- if current_user.customer_id == nil
  div.button-margin
    = form_tag({:controller => 'payments', :action => 'customer_registration'},{ :method => :post}) do
      script.payjp-button[src="https://checkout.pay.jp" data-key="#{ENV.fetch("PAYJP_PUBLIC_KEY")}" data-text="カード情報を登録する"]

table class="table table-bordered"
  thead class="thead-dark table-active "
    tr
      th.text-center = "#"
      th = t('activerecord.attributes.sales_item.name')
      th = t('activerecord.attributes.sales_item.price')
      th = t('activerecord.attributes.sales_item.number_of_ticket')
      th = t('activerecord.attributes.sales_item.effective_date')
      th

  tbody
    - @sales_items.each_with_index do |s,i|
      tr
        td.text-center = i + 1
        td = s.name
        td
          = s.price
          = t('activerecord.attributes.sales_item.yen')
        td
          = s.number_of_ticket
          = t('activerecord.attributes.sales_item.sheet')
        td
          = s.effective_date
          = t('activerecord.attributes.sales_item.date')
        - unless current_user.customer_id == nil
          td = link_to t('activerecord.attributes.link.purchase'), payments_charge_path(id: s.id), method: :post, data: {confirm: t('activerecord.attributes.link.are_you_sure_to_purchase')}, class:"btn btn-warning btn-sm"
  

- if current_user.present? && current_user.customer_id != nil
  div.button-margin
    = form_tag({:controller => 'payments', :action => 'payjpcard_update'},{ :method => :post}) do
      script.payjp-button[src="https://checkout.pay.jp" data-key="#{ENV.fetch("PAYJP_PUBLIC_KEY")}" data-text="カードの変更はこちら" data-submit-text="このカードに変更する"] 

app/views/sales_items/new.html.slim
div.col-md-12
  div class="card"
    div class="card-header text-white bg-secondary text-center" 
      h4 = t('activerecord.attributes.branch.create')
    div class="card-body"
      == render 'shared/errors', obj: @sales_item
      = form_for @sales_item do |f|
        = f.hidden_field :branch_id, value: params[:branch_id]
        == render 'sales_items/form', f: f
        = f.submit  t('activerecord.attributes.link.create'), class:"btn btn-primary button-margin"

app/views/sales_items/show.html.slim
h1 SalesItems#show
p Find me in app/views/sales_items/show.html.slim