config/routes.rb
Rails.application.routes.draw do

  root to: 'reservations#index'

  devise_for :companies, controllers: {
    sessions:      'companies/sessions',
    passwords:     'companies/passwords',
    registrations: 'companies/registrations'
  }
  devise_for :staffs, controllers: {
    sessions:      'staffs/sessions',
    passwords:     'staffs/passwords',
    registrations: 'staffs/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  resources :companies
  resources :branches
  resources :reservations do
    collection do
      get :list
    end
  end
  resources :rooms
  resources :timeframes do
    collection do
      post :single_duplicate
      post :multiple_duplicate
      post :time_based_multiple_duplicate
    end
  end
  resources :users
  resources :tickets
  resources :sales_items do
    collection do
      get :list
      post :purchase
    end
  end
  resources :staffs
  get "locale" => "application#locale", as: "locale"

  post "payments/customer_registration"
  post "payments/payjpcard_update"
  get 'payments/index'
  get "sml" => "payments#sml", as: "sml"
  post "payments/payjp_webhook"
  post "payments/charge"
  post "payments/subscribe"
  post "payments/unsubscribe"
  get "payments" => "payments#index", as: "payments"
  get "payment" => "payments#show", as: "payment"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
  belongs_to :company
  has_many :staffs, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :timeframes, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :sales_items, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true
  validates :address, presence: true
end

app/models/colorlist.rb
class Colorlist < ActiveHash::Base
  self.data = [
    {id: 1, name: "赤(Red)", code: "#B22222"}, {id: 2, name: "青(Blue)", code: "#1E90FF"}, {id: 3, name: "緑(Green)", code: "#228B22"},
    {id: 4, name: "黄色(Yellow)", code: "#FFD700"},  {id: 5, name: "オレンジ(Orange)", code: "#FFA500"}, {id: 6, name: "ピンク(Pink)", code: "#EE82EE"},
    {id: 7, name: "灰色(Gray)", code: "#808080"}, {id: 8, name: "茶色(Brown)", code: "#A0522D"}
  ]
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :users, dependent: :destroy
  has_many :staffs, dependent: :destroy
  has_many :branches, dependent: :destroy
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :timeframe
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :branch
end

app/models/sales_item.rb
class SalesItem < ApplicationRecord
  validates :name, presence: true
  validates :number_of_ticket, presence: true
  validates :branch_id, presence: true
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  belongs_to :company
  belongs_to :branch

  enum status: { general: 1, admin: 3 }

end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :user
end

app/models/timeframe.rb
class Timeframe < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :colorlist
  belongs_to :branch
  belongs_to :room
  has_many :reservations, dependent: :destroy

  TIME_SPAN = 5.freeze
  START_TIME = Time.zone.local(2017, 1, 1, 7, 0).freeze
  END_TIME = Time.zone.local(2017, 1, 1, 23, 0).freeze

  validates :name, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :capacity, presence: true, numericality: true
  validates :color, presence: true
  validate :timeframe_duplicate
  validate :timeframe_span_check
  validate :timeframe_start_time_check
  validate :timeframe_end_time_check

  #バリデーション
  def date
    self.target_date
  end

  def timeframe_duplicate
    if self.branch.present? && Timeframe.where(target_date: target_date).where("room_id = ?", room_id)
      .where("start_time < ?", end_time).where("end_time > ?", start_time).where.not(id: self.id).where(branch_id: self.branch_id).present?
      errors.add(:start_time, ": ご入力いただいた時間帯にすでに時間枠が存在します。")
    end
  end

  def timeframe_span_check
    if start_time && start_time.strftime('%H:%M') >= end_time.strftime('%H:%M')
        errors.add(:start_time, :timeframe_start_time_should_be_smaller_than_end_time)
    end
  end

  def timeframe_start_time_check
    if start_time && start_time.strftime('%H:%M') < self.branch.calendar_start_time.strftime('%H:%M')
      errors.add(:start_time, :timeframe_start_time_should_be_within_calendar_start_time)
    end
  end

  def timeframe_end_time_check
    if end_time && end_time.strftime('%H:%M') > self.branch.calendar_end_time.strftime('%H:%M')
      errors.add(:end_time, :timeframe_end_time_should_be_within_calendar_end_time)
    end
  end


  #判定用
  def self.timeframe_duplicate?(timeframe)
    Timeframe.where("start_time <=?", timeframe.target_date.strftime("%Y-%m-%d") + " " + timeframe.end_time.strftime("%H:%M:%S"))
    .where("end_time >= ?", timeframe.target_date.strftime("%Y-%m-%d") + " " + timeframe.start_time.strftime("%H:%M:%S"))
    .where("room_id = ?", timeframe.room_id).present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :company
  belongs_to :branch
  has_many :reservations, dependent: :destroy
  has_many :tickets, dependent: :destroy
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :find_branch, only: [:show, :edit, :update, :destroy]

  def index
    @branches = company_admin.branches
    @branch = @branches.first
  end

  def show
    @staffs = @branch.staffs
    @users = @branch.users
  end

  def new
    @branch = Branch.new
  end

  def create
    @branch = Branch.new(branch_params)
    @branch.company_id = company_admin.id
    if @branch.save
      redirect_to branches_path(company_id: @branch.id), notice: t('activerecord.attributes.link.created')
    else
      flash.now[:alert] = t('activerecord.attributes.link.failed_to_create')
      render 'new'
    end
  end

  def edit
  end

  def update
    @branch.update(branch_params)
    if @branch.update(branch_params)
      redirect_to branches_path, notice: t('activerecord.attributes.link.updated')
    else
      flash[:notice] = t('activerecord.attributes.link.failed_to_create')
      render 'branches/edit'
    end
  end

  def destroy
    @branch.destroy
    redirect_to branches_path, notice: t('activerecord.attributes.link.canceled')
  end

  private
    def find_branch
        @branch = Branch.find(params[:id])
    end

    def branch_params
      params.require(:branch).permit(:name, :address, :phone, :company_id, :calendar_start_time, :calendar_end_time,
         :makable_reservation_hour_span, :cancelable_reservation_hour_span, :ticket_price, :email, :secret_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def devise_error_messages
    return "" if resource.errors.empty?
    html = ""
    # エラーメッセージ用のHTMLを生成
    messages = resource.errors.full_messages.each do |msg|
    html += <<-EOF
        <div class="error_field alert alert-danger" role="alert">
        <p class="error_msg">#{msg}</p>
        </div>
    EOF
    end
    html.html_safe
  end
end
  

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sales_items_helper.rb
module SalesItemsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/timeframes_helper.rb
module TimeframesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/branches/_form.html.slim
div.col-md-6
  div.form-group
    = f.label :name
    = f.text_field :name, class:"form-control"
div.col-md-6
  div.form-group
    = f.label :phone
    = f.text_field :phone, placeholder: t('activerecord.attributes.branch.phone_comment'), class:"form-control"
div.col-md-12
  div.form-group
    = f.label :email
    = f.text_field :email, class:"form-control"
div.col-md-12
  div.form-group
    = f.label :address
    = f.text_field :address, class:"form-control"
div.col-md-12
  div.form-group
    = f.label :ticket_price
    div.input-group
      = f.number_field :ticket_price, class:"form-control"
      span.input-group-text = t('activerecord.attributes.branch.yen')


div.form-group
  div.col-md-6
    label = t('activerecord.attributes.branch.time_on_calendar')
    br
    = f.datetime_select :calendar_start_time, discard_year: true, discard_month: true, discard_day: true, start_hour: 7, end_hour: 22, minute_step: 60, autofocus: 'true', class:"form-control"
    = " ~ "
    =  f.datetime_select :calendar_end_time, discard_year: true, discard_month: true, discard_day: true, start_hour: 7, end_hour: 22, minute_step: 60, autofocus: 'true', class:"form-control"
  div.col-md-3
    label = t('activerecord.attributes.branch.reservation_limit')
    div.input-group
      = f.number_field :makable_reservation_hour_span, autofocus: 'true', class:"form-control"
      span. = t('activerecord.attributes.branch.before_end_time')
    
  div.col-md-3
    label = t('activerecord.attributes.branch.cancelation_limit')
    div.input-group
      = f.number_field :cancelable_reservation_hour_span, autofocus: 'true', class:"form-control"
      span.input-group-text = t('activerecord.attributes.branch.before_end_time')
  
  div.col-md-12
    br
    label = f.label t('activerecord.attributes.branch.secret_code')
    = f.text_field :secret_code, autofocus: true, class:"form-control"



  

app/views/branches/edit.html.slim
div.row
  div.col-md-12
    div class="card"
      div class="card-header text-white bg-secondary mb-3" 
        h4  = t('activerecord.attributes.branch.edit')
      div class="card-body"
        == render 'shared/errors', obj: @branch
        = form_for @branch, url: branch_path do |f|
          == render 'branches/form', f: f
          = f.submit  t('activerecord.attributes.link.update'), class:"btn btn-success button-margin"
br
br
= link_to :back do 
  button class="btn btn-secondary button-margin" = t("activerecord.attributes.link.back")

app/views/branches/index.html.slim
div
  = link_to t('activerecord.attributes.branch.create'), new_branch_path, class:"btn btn-primary button-margin"

table class="table table-bordered"
  thead class="thead-dark table-active "
    tr
      th = t('activerecord.attributes.branch.name')
      th = t('activerecord.attributes.branch.address')
      th = t('activerecord.attributes.branch.phone')
      th

  tbody
    - if @branches.present?
      - @branches.each do |b| 
        tr
          td = b.name
          td = b.address
          td = b.phone
          td 
            = link_to t('activerecord.attributes.link.edit'), edit_branch_path(id: b.id), class:"btn btn-success button-margin"
            = link_to t('activerecord.attributes.link.delete'), branch_path(id: b.id), method: :delete, data: {confirm: t('activerecord.attributes.link.are_you_sure')}, class:"btn btn-danger button-margin"

app/views/branches/new.html.slim
div.col-md-12
  div class="card"
    div class="card-header text-white bg-secondary text-center" 
      h4 = t('activerecord.attributes.branch.create')
    div class="card-body"
      == render 'shared/errors', obj: @branch
      = form_for @branch do |f|
        == render 'branches/form', f: f
        = f.submit  t('activerecord.attributes.link.create'), class:"btn btn-primary button-margin"


javascript:
  var start_time = document.getElementById("branch_calendar_start_time_4i");
  start_time.value = "10";
  var end_time = document.getElementById("branch_calendar_end_time_4i");
  end_time.value = "22";
  

app/views/branches/show.html.slim
div
    
= link_to t('activerecord.attributes.link.back'), branches_path, class:"btn btn-secondary btn-sm"

javascript:
  jQuery(function(){
    var params = (new URL(document.location)).searchParams;
    var target = params.get('target');
    if (target == "user") {
      $(`.staff`).css('background-color', '#DDDDDD');
      $(`.room`).css('background-color', '#DDDDDD');
    } else if ( target == "staff") {
      $(`.user`).css('background-color', "#DDDDDD" );
      $(`.room`).css('background-color', '#DDDDDD');
    } else if ( target == "room"){
      $(`.user`).css('background-color', "#DDDDDD" );
      $(`.staff`).css('background-color', '#DDDDDD');
    }
  }) 