config/routes.rb
Rails.application.routes.draw do

  root to: 'reservations#index'

  devise_for :companies, controllers: {
    sessions:      'companies/sessions',
    passwords:     'companies/passwords',
    registrations: 'companies/registrations'
  }
  devise_for :staffs, controllers: {
    sessions:      'staffs/sessions',
    passwords:     'staffs/passwords',
    registrations: 'staffs/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  resources :companies
  resources :branches
  resources :reservations do
    collection do
      get :list
    end
  end
  resources :rooms
  resources :timeframes do
    collection do
      post :single_duplicate
      post :multiple_duplicate
      post :time_based_multiple_duplicate
    end
  end
  resources :users
  resources :tickets
  resources :sales_items do
    collection do
      get :list
      post :purchase
    end
  end
  resources :staffs
  get "locale" => "application#locale", as: "locale"

  post "payments/customer_registration"
  post "payments/payjpcard_update"
  get 'payments/index'
  get "sml" => "payments#sml", as: "sml"
  post "payments/payjp_webhook"
  post "payments/charge"
  post "payments/subscribe"
  post "payments/unsubscribe"
  get "payments" => "payments#index", as: "payments"
  get "payment" => "payments#show", as: "payment"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
  belongs_to :company
  has_many :staffs, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :timeframes, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :sales_items, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true
  validates :address, presence: true
end

app/models/colorlist.rb
class Colorlist < ActiveHash::Base
  self.data = [
    {id: 1, name: "赤(Red)", code: "#B22222"}, {id: 2, name: "青(Blue)", code: "#1E90FF"}, {id: 3, name: "緑(Green)", code: "#228B22"},
    {id: 4, name: "黄色(Yellow)", code: "#FFD700"},  {id: 5, name: "オレンジ(Orange)", code: "#FFA500"}, {id: 6, name: "ピンク(Pink)", code: "#EE82EE"},
    {id: 7, name: "灰色(Gray)", code: "#808080"}, {id: 8, name: "茶色(Brown)", code: "#A0522D"}
  ]
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :users, dependent: :destroy
  has_many :staffs, dependent: :destroy
  has_many :branches, dependent: :destroy
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :timeframe
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :branch
end

app/models/sales_item.rb
class SalesItem < ApplicationRecord
  validates :name, presence: true
  validates :number_of_ticket, presence: true
  validates :branch_id, presence: true
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  belongs_to :company
  belongs_to :branch

  enum status: { general: 1, admin: 3 }

end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :user
end

app/models/timeframe.rb
class Timeframe < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :colorlist
  belongs_to :branch
  belongs_to :room
  has_many :reservations, dependent: :destroy

  TIME_SPAN = 5.freeze
  START_TIME = Time.zone.local(2017, 1, 1, 7, 0).freeze
  END_TIME = Time.zone.local(2017, 1, 1, 23, 0).freeze

  validates :name, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :capacity, presence: true, numericality: true
  validates :color, presence: true
  validate :timeframe_duplicate
  validate :timeframe_span_check
  validate :timeframe_start_time_check
  validate :timeframe_end_time_check

  #バリデーション
  def date
    self.target_date
  end

  def timeframe_duplicate
    if self.branch.present? && Timeframe.where(target_date: target_date).where("room_id = ?", room_id)
      .where("start_time < ?", end_time).where("end_time > ?", start_time).where.not(id: self.id).where(branch_id: self.branch_id).present?
      errors.add(:start_time, ": ご入力いただいた時間帯にすでに時間枠が存在します。")
    end
  end

  def timeframe_span_check
    if start_time && start_time.strftime('%H:%M') >= end_time.strftime('%H:%M')
        errors.add(:start_time, :timeframe_start_time_should_be_smaller_than_end_time)
    end
  end

  def timeframe_start_time_check
    if start_time && start_time.strftime('%H:%M') < self.branch.calendar_start_time.strftime('%H:%M')
      errors.add(:start_time, :timeframe_start_time_should_be_within_calendar_start_time)
    end
  end

  def timeframe_end_time_check
    if end_time && end_time.strftime('%H:%M') > self.branch.calendar_end_time.strftime('%H:%M')
      errors.add(:end_time, :timeframe_end_time_should_be_within_calendar_end_time)
    end
  end


  #判定用
  def self.timeframe_duplicate?(timeframe)
    Timeframe.where("start_time <=?", timeframe.target_date.strftime("%Y-%m-%d") + " " + timeframe.end_time.strftime("%H:%M:%S"))
    .where("end_time >= ?", timeframe.target_date.strftime("%Y-%m-%d") + " " + timeframe.start_time.strftime("%H:%M:%S"))
    .where("room_id = ?", timeframe.room_id).present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :company
  belongs_to :branch
  has_many :reservations, dependent: :destroy
  has_many :tickets, dependent: :destroy
end

app/helpers/application_helper.rb
module ApplicationHelper
  def devise_error_messages
    return "" if resource.errors.empty?
    html = ""
    # エラーメッセージ用のHTMLを生成
    messages = resource.errors.full_messages.each do |msg|
    html += <<-EOF
        <div class="error_field alert alert-danger" role="alert">
        <p class="error_msg">#{msg}</p>
        </div>
    EOF
    end
    html.html_safe
  end
end
  

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/timeframes_helper.rb
module TimeframesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_alert.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_errors.html.slim
- if obj.errors.any?
  div.alert.alert-danger
    ul
      - obj.errors.full_messages.each do |msg|
        li
          = msg

      

app/views/shared/_footer.html.erb
<div class="footer">
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <% if current_company.present? %>
      <%= link_to t('app_name'), branches_path, class:"navbar-brand button-color app-title" %>
    <% else %>
      <%= link_to t('app_name'), root_path, class:"navbar-brand button-color app-title"%>
    <% end %>
    <div class="d-none d-lg-block">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
    
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="ms-auto">
          <ul class="navbar-nav">
            <!-- 企業がログインしている時　-->
            <% if current_company.present? %>
              <li class="nav-item"><%= link_to t('activerecord.attributes.link.logout'),destroy_company_session_path, method: :delete, class:"nav-link" %></li>

            <!-- スタッフがログインしている時　-->
            <% elsif current_staff.present? %>
              <li class="nav-item"> <%= link_to t('activerecord.attributes.link.logout'),destroy_staff_session_path, method: :delete, class:"nav-link" %></li>

          <!-- ユーザーがログインしている時　-->
            <% elsif current_user.present? %>
              <li class="nav-item"><%= link_to t('activerecord.attributes.reservation.title'), reservations_path(branch_id: current_user.branch.id, style: "calendar_view"), class:"nav-link" %></li>
              <li class="nav-item"><%= link_to t('activerecord.attributes.reservation.confirmation'), list_reservations_path(branch_id: current_user.branch.id, style: "calendar_view"), class:"nav-link" %></li>
              <li class="nav-item"><%= link_to t('activerecord.attributes.ticket.purchase'), list_sales_items_path(branch_id: current_user.branch.id), class:"nav-link" %></li>
              <li class="nav-item"> <%= link_to t('activerecord.attributes.link.logout'),destroy_user_session_path, method: :delete, class:"nav-link" %></li>
            <% end %>
            <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
              <ul class="navbar-nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= t('activerecord.attributes.language.setting') %>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><%= link_to t('activerecord.attributes.language.japanese'), locale_path(locale: "ja"), class:"dropdown-item" %></li>
                    <li><%= link_to t('activerecord.attributes.language.english'), locale_path(locale: "en"), class:"dropdown-item" %></li>
                  </ul>
                </li>
              </ul>
            </div>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_sidebar-lg.html.erb
<% if company_admin %>
  <ul class="list-group">
    <li class="<%= 'active' if controller_name == "branches" && action_name == "index" %> list-group-item">
      <%= link_to t('activerecord.attributes.branch.title'), branches_path, class:"text" %>
    </li>
    <% if company_admin.branches.count > 0 %>
      <li class="<%= 'active' if controller_name == "users" && action_name == "index" %> list-group-item">
        <%= link_to t('activerecord.attributes.user.title'), users_path(branch_id: company_admin.branches.first.id), class:"text" %>
      </li>
      <li class="<%= 'active' if controller_name == "staffs" && action_name == "index" %> list-group-item">
        <%= link_to t('activerecord.attributes.staff.title'), staffs_path(branch_id: company_admin.branches.first.id), class:"text"%>
      </li>
      <li class="<%= 'active' if controller_name == "reservations" && action_name == "index" %> list-group-item">
        <%= link_to t('activerecord.attributes.reservation.calendar'), reservations_path(branch_id: company_admin.branches.first.id), class:"text"%>
      </li>
      <li class="<%= 'active' if controller_name == "reservations" && action_name == "list" %> list-group-item">
        <%= link_to t('activerecord.attributes.reservation.list'), list_reservations_path(branch_id: company_admin.branches.first.id), class:"text"%>
      </li>
      <li class="<%= 'active' if controller_name == "sales_items" && action_name == "index" %> list-group-item">
        <%= link_to t('activerecord.attributes.sales_item.title'), sales_items_path(branch_id: company_admin.branches.first.id), class:"text"%>
      </li>
      <li class="<%= 'active' if controller_name == "payments" && action_name == "index" %> list-group-item">
        <%= link_to t('activerecord.attributes.payments.sales_management'), payments_path(branch_id: company_admin.branches.first.id), class:"text"%>
      </li>
    <% end %>
    <% if current_company.present? %>
      <li class="<%= 'active' if controller_name == "registrations" && action_name == "edit" %> list-group-item">
        <%= link_to t('activerecord.attributes.company.edit_registration'), edit_company_registration_path, class:"text" %></li>
      </li>
    <% end %>
    <% if current_company.present? && current_company == Company.first %>
      <li class="<%= 'active' if controller_name == "payments" && action_name == "sml" %> list-group-item">
        <%= link_to t('activerecord.attributes.payments.sml'), sml_path, class:"text" %></li>
      </li>
    <% end %>
  </ul>

<% elsif current_staff.present? && current_staff.status == "general" %>
  <ul class="list-group">
    <li class="<%= 'active' if controller_name == "reservations" && action_name == "index" %> list-group-item">
      <%= link_to t('activerecord.attributes.reservation.calendar'), reservations_path(branch_id: current_staff.company.branches.first.id), class:"text"%>
    </li>
    <li class="<%= 'active' if controller_name == "reservations" && action_name == "list" %> list-group-item">
        <%= link_to t('activerecord.attributes.reservation.list'), list_reservations_path(branch_id: current_staff.company.branches.first.id), class:"text"%>
      </li>
  </ul>
<% elsif current_user.present? %>
  <li class="<%= 'active' if controller_name == "reservations" && action_name == "index" %> list-group-item">
    <%= link_to t('activerecord.attributes.reservation.title'), reservations_path, class:"text"%>
  </li>
<% end %>

<script>
  $(document).ready(function () {
    // $('.navbar-collapse').addClass('show')
  });

  var judge = document.getElementById("judge-collape");
  function addAnswer() {
    if( !judge.classList.contains("show") ) {
      judge.classList.add('show');
    } else {
      judge.classList.remove('show');
      judge.classList.add('hide');
    }
  }
  
  var trigger = document.querySelectorAll(".text");

  trigger.forEach(function(target) {

    target.addEventListener('click', function() {
      judge.classList.remove('show');
      judge.classList.add('hide');
    });
  });

</script>

app/views/shared/_sidebar-sm.html.erb
<input type="checkbox" class="openSidebarMenu" id="openSidebarMenu">
<label for="openSidebarMenu" class="sidebarIconToggle">
  <div class="spinner diagonal part-1"></div>
  <div class="spinner horizontal"></div>
  <div class="spinner diagonal part-2"></div>
</label>
<div id="sidebarMenu">
  <ul class="sidebarMenuInner">
    <% if company_admin.present? && company_admin.branches.count > 0 %>
      <li class="<%= 'active' if controller_name == "branches" && action_name == "index" %>">
        <%= link_to t('activerecord.attributes.branch.title'), branches_path, class:"text" %>
      </li>
      <li class="<%= 'active' if controller_name == "users" && action_name == "index" %>">
        <%= link_to t('activerecord.attributes.user.title'), users_path(branch_id: company_admin.branches.first.id), class:"text" %>
      </li>
      <li class="<%= 'active' if controller_name == "staffs" && action_name == "index" %>">
        <%= link_to t('activerecord.attributes.staff.title'), staffs_path(branch_id: company_admin.branches.first.id), class:"text"%>
      </li>
      <li class="<%= 'active' if controller_name == "reservations" && action_name == "index" %>">
        <%= link_to t('activerecord.attributes.reservation.calendar'), reservations_path(branch_id: company_admin.branches.first.id), class:"text"%>
      </li>
      <li class="<%= 'active' if controller_name == "reservations" && action_name == "list" %>">
        <%= link_to t('activerecord.attributes.reservation.list'), list_reservations_path(branch_id: company_admin.branches.first.id), class:"text"%>
      </li>
      <li class="<%= 'active' if controller_name == "sales_items" && action_name == "index" %>">
        <%= link_to t('activerecord.attributes.sales_item.title'), sales_items_path(branch_id: company_admin.branches.first.id), class:"text"%>
      </li>
      <li class="<%= 'active' if controller_name == "payments" && action_name == "index" %>">
        <%= link_to t('activerecord.attributes.payments.sales_management'), payments_path(branch_id: company_admin.branches.first.id), class:"text"%>
      </li>
    <% end %>
    <% if current_company.present? %>
      <li class="<%= 'active' if controller_name == "registrations" && action_name == "edit" %>">
        <%= link_to t('activerecord.attributes.company.edit_registration'), edit_company_registration_path, class:"text" %></li>
      </li>
    <% end %>
    <% if current_company.present? && current_company == Company.first %>
      <li class="<%= 'active' if controller_name == "payments" && action_name == "sml" %>">
        <%= link_to t('activerecord.attributes.payments.sml'), sml_path, class:"text" %></li>
      </li>
    <% end %>
    <% if current_company.present? %>
      <li class="nav-item"><%= link_to t('activerecord.attributes.link.logout'),destroy_company_session_path, method: :delete, class:"nav-link" %></li>

    <!-- スタッフがログインしている時　-->
    <% elsif current_staff.present? %>
      <li class="nav-item"> <%= link_to t('activerecord.attributes.link.logout'),destroy_staff_session_path, method: :delete, class:"nav-link" %></li>

  <!-- ユーザーがログインしている時　-->
    <% elsif current_user.present? %>
      <li class="nav-item"><%= link_to t('activerecord.attributes.reservation.title'), reservations_path(branch_id: current_user.branch.id, style: "calendar_view"), class:"nav-link" %></li>
      <li class="nav-item"><%= link_to t('activerecord.attributes.reservation.confirmation'), list_reservations_path(branch_id: current_user.branch.id, style: "calendar_view"), class:"nav-link" %></li>
      <li class="nav-item"><%= link_to t('activerecord.attributes.ticket.purchase'), list_sales_items_path(branch_id: current_user.branch.id), class:"nav-link" %></li>
      <li class="nav-item"> <%= link_to t('activerecord.attributes.link.logout'),destroy_user_session_path, method: :delete, class:"nav-link" %></li>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= t('activerecord.attributes.language.setting') %>
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            <li><%= link_to t('activerecord.attributes.language.japanese'), locale_path(locale: "ja"), class:"dropdown-item" %></li>
            <li><%= link_to t('activerecord.attributes.language.english'), locale_path(locale: "en"), class:"dropdown-item" %></li>
          </ul>
        </li>
      </ul>
    </div>
  </ul>
</div>

<script>
  $(document).ready(function () {
    // $('.navbar-collapse').addClass('show')
  });

  var judge = document.getElementById("judge-collape");
  function addAnswer() {
    if( !judge.classList.contains("show") ) {
      judge.classList.add('show');
    } else {
      judge.classList.remove('show');
      judge.classList.add('hide');
    }
  }
  
  var trigger = document.querySelectorAll(".text");

  trigger.forEach(function(target) {

    target.addEventListener('click', function() {
      judge.classList.remove('show');
      judge.classList.add('hide');
    });
  });

</script>